### ISSUE TITLE
Moves animate OpMons

### ISSUE THREAD

**Issue by cyriellecentori** [OpMonTeam/OpMon#33]
The feature to add is not full animations like in the Pokemon games. For now, the only thing to do will be to add special transformations for OpMons (Translations, rotations and rescaling) for different moves.
Adding backgrounds and sprite animations will be something to do later. However, it is still possible to do it now if the people working on it are really motivated, but they will have to create graphics for it.

**Comment by Kuromeruk** [comment]
I would like to work on this feature

**Comment by cyriellecentori** [comment]
No problem! If you have any question or need any clarification, don’t hesitate to ask here or on the [Discord server](https://discord.gg/Yj2Fwqvj2G)!
