### ISSUE TITLE
Update to Godot 4

### ISSUE THREAD

**Issue by milkyroute** [OpMonTeam/OpMon#61]
Current problems:

- [x] Camera not working
- [x] Characters’ movements not working
- [x] Battles not working
- [x] HP bar bug
- [x] Dialogs not working

**Comment by DavidLiang1129** [comment]
Glad to see this game updated! By the way, to introduce myself, I am from China and am the unofficial Chinese translator for another monster capture game, Tuxemon

**Comment by milkyroute** [comment]
Welcome, then! I’m back from a hiatus I’ll sadly probably have to get back to in September but I’ll try to work on the game as much as I can this summer.

**Comment by DavidLiang1129** [comment]
> Current problems:
> 
> - [ ] Camera not working
> - [ ] Characters’ movements not working
> - [ ] Map layers 2 and 3 gone
> - To be continued…

That's okay, I can wait. Anyway, thank you for your dedication to OpMon

**Comment by DavidLiang1129** [comment]
> Welcome, then! I’m back from a hiatus I’ll sadly probably have to get back to in September but I’ll try to work on the game as much as I can this summer.

That's okay, I can wait. Anyway, thank you for your dedication to OpMon

**Comment by milkyroute** [comment]
Done in #62!
